### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by ShadowCoder69** [Mithion/GriefGuardian#2]
Are you gonna update this mod to Forge 1.8?
Because else i will do

**Comment by Mithion** [comment]
have at it.

**Comment by Ravian2002** [comment]
Wow that was a quick reaction...
I will try to update it to 1.8 then :-)
I will let you know when its done

**Comment by Mithion** [comment]
Heh they come to my phone...which is glued to my hip when I'm at work.
Sounds great!  Let me know if you have any questions about how/why I did what I did in certain sections.

**Comment by Ravian2002** [comment]
Ah i see
I will sure do that :-)

**Comment by Ravian2002** [comment]
I've a question already xD
Why did you use in *com.mithion.griefguardian.claims.Claim.getBounds()* copy?
I can't find an equivalent, and you can also just return the object because java is ByValue

**Comment by Mithion** [comment]
First question: mainly a C++ background in programming.  I'm paranoid :P  Feel free to change it.
Second question:  Use the ForgeDirection enum.  The comments on each enum value in forge indicate which axis and sign it uses.

**Comment by Ravian2002** [comment]
Thnx!
Now i can go further.

**Comment by HoldYourWaffle** [comment]
I may update this mod to 1.9, but I think i'll then rewrite a big part so I have an better understanding of whats going on.

**Comment by HoldYourWaffle** [comment]
After looking further into the code and the errors in an 1.9 environment I think I'm gonna build it from the ground up. Of course I'll use your mod as learning-thingy and credit you because I can :+1:

**Comment by HoldYourWaffle** [comment]
Didn't I close this?

**Comment by HoldYourWaffle** [comment]
Now I did :)

**Comment by HoldYourWaffle** [comment]
Whoops
